version: '3.7'

networks:
  rschat-net:
    driver: bridge

volumes:
  grafana-storage:
  rschat-logs:
  rschat-db:

x-logging: &default-logging
  driver: json-file
  options:
    tag: "{{.Name}}"

services:
  rschat:
    image: rs-chat:latest
    container_name: rschat
    env_file: ./env/.env.prod
    ports:
      - "4040:4040"
    volumes:
      - rschat-logs:/app/logs
    networks:
      - rschat-net
    depends_on:
      - rschat-db
    logging: *default-logging
    healthcheck:
      test: curl -f https://localhost:4040/api/v1/health --insecure -s > /dev/null || exit 1
      interval: 2m
      timeout: 10s
      retries: 3

  rschat-db:
    image: mysql:latest
    container_name: rschat-db
    env_file: ./env/.env.db
    ports:
      - "4041:3306"
    volumes:
      - ./src/main/resources/db/rs_chat.sql:/docker-entrypoint-initdb.d/1.sql
      - rschat-db:/var/lib/mysql
    networks:
      - rschat-net
    logging: *default-logging

  prometheus:
    # Grafana config -> URL = http://prometheus:9090, other settings are default
    image: prom/prometheus:v2.40.5
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - "4043:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - rschat
      - rschat-db
    networks:
      - rschat-net
    logging: *default-logging

  grafana:
    image: grafana/grafana-oss:9.3.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - "4046:3000"
    links:
      - prometheus:prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - rschat
    env_file:
      - ./env/.env.grafana
    networks:
      - rschat-net
    logging: *default-logging

  loki:
    # Grafana config -> URL = http://loki:3100, other settings are default
    image: grafana/loki:2.7.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "4045:3100"
    volumes:
      - ./config/loki.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    depends_on:
      - promtail
    networks:
      - rschat-net
    logging: *default-logging

  promtail:
    image: grafana/promtail:2.7.0
    container_name: promtail
    restart: unless-stopped
    ports:
      - "4044:9080"
    volumes:
      - /var/log:/var/log
      - ./config/promtail.yaml:/etc/promtail/promtail.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - rschat
    networks:
      - rschat-net
    logging: *default-logging

  # Utilities
  nsfwpy:
    image: nsfwpy:latest
    container_name: nsfwpy
    ports:
      - "4042:4042"
    networks:
      - rschat-net
    logging: *default-logging
    healthcheck:
      test: curl -f http://localhost:4042/api/v1/health -s > /dev/null || exit 1
      interval: 2m
      timeout: 10s
      retries: 3
