version: "3.7"
services:
  # RS Chat application
  rs-chat:
    image: rs-chat
    restart: on-failure
    env_file:
      - .env.dev
    volumes:
      - ./logs/rs_chat-app.log:/tmp/rs_chat-app.log
      - ./logs/rs_chat-warns.log:/tmp/rs_chat-warns.log
    ports:
      - "4040:4040"
    depends_on:
      - rschat-db
      - localstack
    networks:
      - rschat-net

  rschat-db:
    image: mysql:latest
    env_file:
      - .env.dev # Todo extract database env variables to a separate file
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - rschat-net

  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  my-db:

networks:
  rschat-net:
