version: "3.7"
services:
  # RS Chat application
  rs-chat:
    image: rs-chat
    restart: on-failure
    env_file:
      - .env.dev
    volumes:
      - ./logs/rs_chat-app.log:/tmp/rs_chat-app.log
      - ./logs/rs_chat-warns.log:/tmp/rs_chat-warns.log
    ports:
      - "4040:4040"
    depends_on:
      - rschat-db
      - localstack
    networks:
      - rschat-net

  rschat-db:
    image: mysql:latest
    env_file:
      - .env.dev # Todo extract database env variables to a separate file
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./src/main/resources/db/rs_chat.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - rschat-net

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # ext services port range
      - "127.0.0.1:53:53"                # DNS config
      - "127.0.0.1:53:53/udp"            # DNS config
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  my-db:
  localstack-data:

networks:
  rschat-net:
