version: '3.7'

networks:
  rschat-net:
    driver: bridge

volumes:
  grafana-storage:
  localstack-data:
  rschat-logs:
  rschat-db:

x-logging: &default-logging
  driver: json-file
  options:
    tag: "{{.Name}}"

services:
  rschat:
    image: rs-chat:latest
    container_name: rschat
    env_file: ./env/.env.prod
    ports:
      - "4040:4040"
    expose: [ 4040 ]
    volumes:
      - rschat-logs:/app/logs
    networks:
      - rschat-net
    depends_on:
      - rschat-db
#      - rschat-localstack-aws
    logging: *default-logging

  rschat-db:
    image: mysql:latest
    container_name: rschat-db
    env_file: ./env/.env.db
    ports:
      - "4041:3306"
    expose: [ 4041 ]
    volumes:
      - ./src/main/resources/db/rs_chat.sql:/docker-entrypoint-initdb.d/1.sql
      - rschat-db:/var/lib/mysql
    networks:
      - rschat-net
    logging: *default-logging

  #  rschat-localstack-aws:
  #    image: localstack/localstack
  #    container_name: rschat-localstack
  #    ports:
  #      - "4042:4566"
  #    environment:
  #      - EAGER_SERVICE_LOADING=1
  #      - SERVICES=s3
  #      - DEBUG=1
  #      - DOCKER_HOST=unix:///var/run/docker.sock
  #      - S3_DIR=~/.appdata/rschat/data
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock
  #      - localstack-data:${HOME}/.appdata/rschat/data
  #    networks:
  #      - rschat-net
  #    logging: *default-logging

  prometheus:
    image: prom/prometheus:v2.40.5
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - "4043:9090"
    expose: [ 4043 ]
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - rschat
      - rschat-db
    networks:
      - rschat-net
    logging: *default-logging

  grafana:
    image: grafana/grafana-oss:9.3.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - "4046:3000"
    expose: [ 4046 ]
    links:
      - prometheus:prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - rschat
    env_file:
      - ./env/.env.grafana
    networks:
      - rschat-net
    logging: *default-logging

  loki:
    image: grafana/loki:2.7.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "4045:3100"
    volumes:
      - ./config/loki.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    depends_on:
      - promtail
    networks:
      - rschat-net
    logging: *default-logging

  promtail:
    image: grafana/promtail:2.7.0
    container_name: promtail
    restart: unless-stopped
    ports:
      - "4044:9080"
    volumes:
      - /var/log:/var/log
      - ./config/promtail.yaml:/etc/promtail/promtail.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - rschat
    networks:
      - rschat-net
    logging: *default-logging
