version: '3.7'

services:
  rschat:
    image: rs-chat:latest
    container_name: rschat
    env_file: ./env/.env.docker
    environment:
      - DOCKER=true
    ports:
      - "4040:4040"
    networks:
      - rschat-net-db
    depends_on:
      - rschat-db
      - rschat-localstack-aws

  rschat-db:
    image: mysql:latest
    container_name: rschat-db-host
    env_file: ./env/.env.db
    ports:
      - "3306"
    volumes:
      - ./src/main/resources/db/rs_chat.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - rschat-net-db

  rschat-localstack-aws:
    image: localstack/localstack
    container_name: localstack-host
    ports:
      - "4566"
      - "4571"
    environment:
      - EAGER_SERVICE_LOADING=1
      - SERVICES=s3
      - DEBUG=1
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - rschat-net-db

  prometheus:
    image: prom/prometheus:v2.40.5
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - rschat
      - rschat-db
    networks:
      - rschat-net-db

  grafana:
    image: grafana/grafana-oss:9.3.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - "9091:3000"
    links:
      - prometheus:prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    env_file:
      - ./env/.env.grafana

networks:
  rschat-net-db:
    driver: bridge

volumes:
  grafana-storage:
