version: '3.7'

services:
  rschat:
    image: rs-chat
    env_file: ./env/.env.docker
    environment:
      - DOCKER=true
    ports:
      - "4041:4041"
#    expose:
#      - 4041
    networks:
      - rschat-net-db
    depends_on:
      - rschat-db
      - rschat-localstack-aws

  rschat-db:
    image: mysql:latest
    container_name: rschat-db-host
    env_file: ./env/.env.db
    ports:
      - "3306"
    volumes:
      - ./src/main/resources/db/rs_chat.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - rschat-net-db

  rschat-localstack-aws:
    image: localstack/localstack
    container_name: localstack-host
    ports:
      - "4566"
      - "4571"
    environment:
      - EAGER_SERVICE_LOADING=1
      - SERVICES=s3
      - DEBUG=1
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - rschat-net-db

networks:
  rschat-net-db:
    driver: bridge
