# This file serves as the agent configuration to interact with the
# docker compose environment.
#
# You should pass the following command line flags when running the agent
# locally and using this file:
#
#   -enable-features=integrations-next -config.expand-env -config.enable-read-api
#
# -enable-features=integrations-next is required as the file is configured for
# the integrations revamp.
#
# -config.expand-env is required to expand environment variables. Environment
# variables are used when running the agent inside of docker-compose to connect
# to the other services. When running the agent externally, the expressions will
# default to the appropriate values of the exposed ports.
#
# -config.enable-read-api is optional, but allows you to invoke the /-/config
# endpoint to examine the generated config.

server:
  log_level: debug
  http_listen_port: 4042
#  grpc_listen_port: 0

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: system
          static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                __path__: /var/log/*.log
      clients:
        - url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
          basic_auth:
            username: 332857
            password: ${GRAFANA_API_KEY}
      target_config:
        sync_period: 10s

traces:
  configs:
    - name: default
      remote_write:
        - endpoint: tempo-eu-west-0.grafana.net:443
          basic_auth:
            username: 329370
            password: ${GRAFANA_API_KEY}
      receivers:
        otlp:
          protocols:
            grpc: # This or http?

metrics:
  configs:
    - name: rs-chat-observability
      remote_write:
        - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
          basic_auth:
            username: 667773
            password: ${GRAFANA_API_KEY}
      scrape_configs:
        - job_name: rs-chat-observability
          scrape_interval: 10s
          static_configs:
            - targets:
                - rs-chat-observability:4040
          metric_relabel_configs:
            - source_labels: [ 'trace_id' ]
              target_label: 'traceID'
  global:
    scrape_interval: 10s
    external_labels:
      monitor: rs-chat-observability
    wal_directory: /tmp/grafana-agent-wal
