global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'rs-chat-api'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'rschat:4040' ]
        labels:
          application: 'RS Chat API'
