name: Java Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      SHOW_SQL: ${{ secrets.SHOW_SQL }}
      S3_ENDPOINT_URI: ${{ secrets.S3_ENDPOINT_URI }}
      S3_ENDPOINT_URI_FOR_FILES: ${{ secrets.S3_ENDPOINT_URI_FOR_FILES }}
      NSFW_API_URL: ${{ secrets.NSFW_API_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Clean
        run: mvn -B clean --file pom.xml
      - name: Compile
        run: mvn -B compile --file pom.xml
      - name: Perform unit tests
        run: mvn -B test --file pom.xml -Dtest="rs.chat.unit.**"
      - name: Perform integration tests
        run: mvn -B test --file pom.xml -Dtest="rs.chat.integration.**"
